
format = """
$directory\
$git_branch$git_status\
$direnv
$character
"""

[character]
success_symbol = "[>>](white)"
error_symbol = "[>>](red)"

[directory]
style = "cyan"
truncation_length = 0
truncate_to_repo = false
use_logical_path = false

[git_branch]
format = "[$branch]($style) "
style = "blue"

[git_status]
style = "fg:green"
format = '([\[$all_status$ahead_behind\]]($style))'
conflicted = "!"
modified = "*"
staged = "+$count "
untracked = "?"
ahead = "^$count "
behind = "-$count "
diverged = "^$ahead_count-$behind_count "

[direnv]
format = '[($symbol:$rc_path)]($style)'
style = 'fg:003'
disabled = false

